### ISSUE TITLE
Please Remove ending white space in name of Directory (December 02)

### ISSUE THREAD

**Issue by MSRishab007** [SVCE-ACM/A-December-Of-Algorithms-2023#31]
The White Space in name of Directory (December 02) is creating issue while cloning in Windows. It is known issue with white spaces in file path while cloning in Windows. Please consider removing all leading and ending white spaces.

Reference: https://github.com/orgs/community/discussions/61503

Thank you

**Comment by sreevathsan22** [comment]
Thank you for bringing this issue to our notice! We have resolved the issue
